services:
  api:
    build: ./api
    ports:
      - "8080:8080"
    volumes:
      - shared_data:/shared_data
    depends_on:
      - rabbitmq
      #     - postgres

  rabbitmq:
    image: rabbitmq:3.13-management # TODO: Change back if being deployed# rabbitmq:latest
    ports:
      - "5672:5672"
      - "15672:15672"
  # postgres:
  #   image: postgres:latest
  #   environment:
  #     POSTGRES_DB: postgres
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #   ports:
  #     - "5432:5432"

  worker:
    build: ./worker
    volumes:
      - shared_data:/shared_data
    depends_on:
      - rabbitmq
      # - postgres

volumes:
  shared_data:
